drop table if exists `general_orders`;
create table `general_orders` (
	id	INTEGER PRIMARY KEY AUTOINCREMENT,
	order_no	varchar(512)	not null,
	user_id	INTEGER	not null,
	op_id	varchar(512)	,
	order_type	varchar(512)	,
	order_status	varchar(512)	not null,
	pay_status	varchar(512)	not null,
	delivery_status	varchar(512)	,
	products_id	INTEGER	not null,
	quality	INTEGER	not null,
	total_amount	DECIMAL(18,6)	not null,
	discount_amount	DECIMAL(18,6)	,
	shipping_fee	DECIMAL(18,6)	,
	actual_amount	DECIMAL(18,6)	not null,
	payment_channel	varchar(512)	,
	payment_order_id	varchar(512)	,
	payment_time	DATETIME	,
	payment_amount	DECIMAL(18,6)	,
	shipping_method	varchar(512)	,
	shipping_address	varchar(512)	,
	shipping_company	varchar(512)	,
	tracking_number	varchar(512)	,
	tel	varchar(512)	,
	recipient	varchar(512)	,
	create_time	DATETIME	not null,
	update_time	DATETIME	not null,
	cancel_time	DATETIME	,
	complete_time	DATETIME	,
	deliver_time	DATETIME	,
	refund_id	varchar(512)	,
	refund_no	varchar(512)	,
	refund_type	varchar(512)	,
	refund_amount	DECIMAL(18,6)	,
	refund_reason	varchar(512)	,
	refund_status	varchar(512)	,
	remark	varchar(512)	,
	is_deleted	INTEGER	,
	table_name	varchar(512)	,
	field_name	varchar(512)	
);